Base64 encoding and decoding
Lazychain/solidity-contracts pull request #2
Opened 2024-11-10 12:37 UTC by coderSomya

This PR adds a library for base64 encoding and decoding with custom table support for safe url parsing.
Added two internal functions.
- **_encode**: Encodes `bytes` data into a base64-like string using a custom encoding table, with optional padding.
- **_decode**: Decodes a base64-like string back to `bytes` using a custom decoding table, handling padding.

to test
```
forge test
```

2024-11-11 08:32 UTC, pablin-dev requested changes

2024-11-11 08:32 UTC, pablin-dev commented on test/TestBase64.t.sol
> +    function testEncodeURL() public {
URL test should contain `file` or `urls`. For example:
- URL=`"http://pepe.com:8545"`; // aHR0cDovL3BlcGUuY29tOjg1NDU= ;  
- URL=`file://pepe.json` ZmlsZTovL3BlcGUuanNvbg==

2024-11-11 08:32 UTC, pablin-dev commented on test/TestBase64.t.sol
> +        bytes memory data = bytes("Test encoding and decoding round-trip URL!");
Same as previous.

2024-11-11 08:32 UTC, pablin-dev commented on contracts/utils/Base64.sol
> +    function _encode(bytes memory data, string memory table, bool withPadding) private pure returns (string memory) {
- Is there a `max` lenght for `data` input on `_decode()` and `_encode()`?

2024-11-11 08:36 UTC, pablin-dev commented
One more question: did `bun` have any issue with the JavaScript side? I notice you change it in your PR for `yarn`.

2024-11-13 10:18 UTC, coderSomya commented on contracts/utils/Base64.sol
> +    function _encode(bytes memory data, string memory table, bool withPadding) private pure returns (string memory) {
it will be good to have it. will see to it. thanks

2024-11-13 10:21 UTC, coderSomya commented
> One more question: did `bun` have any issue with the JavaScript side? I notice you change it in your PR for `yarn`.

No issues with bun, i've been using that itself for package management. My change is only a spelling correction in package.json besides the base64 stuff.

2024-11-18 09:30 UTC, pablin-dev approved these changes
LGTM! Good work! You can merge it.

2024-11-21 06:42 UTC, merged