chore::> Staker contract
Lazychain/solidity-contracts pull request #48
Opened 2024-12-29 05:38 UTC by PsychoPunkSage

# Pull Request

## Description
Implements NFT staking contract supporting ERC721 and ERC1155 tokens with basic staking/unstaking functionality. Uses OpenZeppelin for security standards and includes stake duration tracking.

## Proposed solution
1. Base Contract Setup
 * Implement staking functions for ERC721/1155
 * Add withdrawal mechanism
 * Set up stake tracking system

2. Security Implementation
 * Add ReentrancyGuard
 * Implement proper access controls
 * Set up safe transfer handlers

3. Testing
  * Test staking/unstaking flows
  * Verify security measures

## Checklist

Checklist:
    - [ ]Tests
    - [ ]Documentation

2024-12-29 05:39 UTC, PsychoPunkSage commented
Tests will be covered in different PR.

2024-12-30 08:02 UTC, pablin-dev requested changes
I think `staking period` on constructor is neccesary. Also when staking, checking (using the interface impl) if an ERC721 or ERC1155 is need it.

2024-12-30 11:02 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function stakeERC721(address tokenAddress, uint256 tokenId) external nonReentrant {
I think for simple staking of `ERC721` and `ERC1155` tokens, the functions don't need to be payable unless we want users to:
1. Pay some ETH/native token fee for staking <we are currently not using `staking_fees`>
2. Add stake amount in ETH along with NFT staking

2024-12-30 11:02 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function stakeERC1155(address tokenAddress, uint256 tokenId, uint256 amount) external nonReentrant {
I think for simple staking of ERC721 and ERC1155 tokens, the functions don't need to be payable unless we want users to:

1. Pay some ETH/native token fee for staking <we are currently not using staking_fees>
2. Add stake amount in ETH along with NFT staking

2024-12-30 11:04 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +        IERC1155 nft = IERC1155(tokenAddress);
Ok

2024-12-30 11:08 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +        IERC1155 nft = IERC1155(tokenAddress);
Done

2024-12-30 11:08 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +        IERC721 nft = IERC721(tokenAddress);
Done

2024-12-30 11:08 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function unStake(uint256 index) external {
I think for simple staking of ERC721 and ERC1155 tokens, the functions don't need to be payable unless we want users to:

1. Pay some ETH/native token fee for staking <we are currently not using staking_fees>
2. Add stake amount in ETH along with NFT staking

2024-12-30 11:16 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    constructor() Ownable(msg.sender) {}
I am calculating the `staking period` based on the 
`current time - time @staking`

I don't think it needs to be added to the constructor....

2024-12-30 11:20 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +        stakes[msg.sender][index] = stakes[msg.sender][stakes[msg.sender].length - 1];
What this code does is...
1. It overwrites the element at `index` with the last element of the array
2. Then `removes` the last element with pop()

Ex...
if I have array [A, B, C, D] and want to remove index 1 (B):
- First step: [A, D, C, D] (D overwrites B)
- After pop: [A, D, C] (last D is removed)

2024-12-30 15:26 UTC, coderSomya commented on contracts/apps/staker/stake.sol
> +    function stakeERC1155(address tokenAddress, uint256 tokenId, uint256 amount) external nonReentrant {
i see a lot of code is common between ```stakeERC721``` and ```stakeERC1155```.
we can try to club the reusable parts. that would make it more generic and extendable if tomorrow we want to support a new ercXYZ.

2024-12-30 15:28 UTC, coderSomya commented on contracts/apps/staker/stake.sol
> +        if (stake.isERC1155) {
@PsychoPunkSage yes i think so. staking period would then determine a time before which the staker cannot withdraw the nft.

2024-12-30 15:37 UTC, coderSomya requested changes
Overall looks fine. Possible minor adjustments are in comments.

2024-12-31 05:49 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function stakeERC1155(address tokenAddress, uint256 tokenId, uint256 amount) external nonReentrant {
Good Call
DOne

2024-12-31 05:58 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +        if (stake.isERC1155) {
Done

2024-12-31 10:41 UTC, pablin-dev commented on contracts/apps/staker/stake.sol
> +    function stakeERC1155(address tokenAddress, uint256 tokenId, uint256 amount) external nonReentrant {
Yes, we want the users to pay some native token fee for staking ( protocol revenue ) which is the only way that as a protocol to obtain a `cash flow` that support our dev/product team salaries on long term.
No, we dont need that the user stake an amount of native token, only the nft staking.

2024-12-31 14:57 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function stakeERC1155(address tokenAddress, uint256 tokenId, uint256 amount) external nonReentrant {
DOne

2024-12-31 14:57 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function stakeERC721(address tokenAddress, uint256 tokenId) external nonReentrant {
Done

2024-12-31 14:57 UTC, PsychoPunkSage commented on contracts/apps/staker/stake.sol
> +    function unStake(uint256 index) external {
DOne

2024-12-31 15:02 UTC, PsychoPunkSage commented
@pablin-dev 
Basic template is ready...
After reading [this](https://github.com/Lazychain/docs/blob/main/learn/stories/0003-nft-staking.md) n [this](https://github.com/Lazychain/docs/blob/main/learn/stories/0004-nft-unstaking.md)

there are some functionalities left... (which is currently not tackled)....
Since I don't want PR to get too long.... I will make a separate PR to upgrade this `staker contract` to match those readings

2025-01-01 08:37 UTC, pablin-dev approved these changes
LGTM!

2025-01-01 12:26 UTC, merged